const countries = [
    { label: "Afghanistan", value: "AFN", code: "AFG", timezone: "Asia/Kabul" },
    { label: "Åland Islands", value: "EUR", code: "ALA", timezone: "Europe/Mariehamn" },
    { label: "Albania", value: "ALL", code: "ALB", timezone: "Europe/Tirane" },
    { label: "Algeria", value: "DZD", code: "DZA", timezone: "Africa/Algiers" },
    { label: "American Samoa", value: "USD", code: "ASM", timezone: "Pacific/Pago_Pago" },
    { label: "Andorra", value: "EUR", code: "AND", timezone: "Europe/Andorra" },
    { label: "Angola", value: "AOA", code: "AGO", timezone: "Africa/Luanda" },
    { label: "Anguilla", value: "XCD", code: "AIA", timezone: "America/Anguilla" },
    { label: "Antarctica", value: null, code: "ATA", timezone: "Antarctica/McMurdo" },
    { label: "Antigua and Barbuda", value: "XCD", code: "ATG", timezone: "America/Antigua" },
    { label: "Argentina", value: "ARS", code: "ARG", timezone: "America/Argentina/Buenos_Aires" },
    { label: "Armenia", value: "AMD", code: "ARM", timezone: "Asia/Yerevan" },
    { label: "Aruba", value: "AWG", code: "ABW", timezone: "America/Aruba" },
    { label: "Australia", value: "AUD", code: "AUS", timezone: "Australia/Sydney" },
    { label: "Austria", value: "EUR", code: "AUT", timezone: "Europe/Vienna" },
    { label: "Azerbaijan", value: "AZN", code: "AZE", timezone: "Asia/Baku" },
    { label: "Bahamas", value: "BSD", code: "BHS", timezone: "America/Nassau" },
    { label: "Bahrain", value: "BHD", code: "BHR", timezone: "Asia/Bahrain" },
    { label: "Bangladesh", value: "BDT", code: "BGD", timezone: "Asia/Dhaka" },
    { label: "Barbados", value: "BBD", code: "BRB", timezone: "America/Barbados" },
    { label: "Belarus", value: "BYN", code: "BLR", timezone: "Europe/Minsk" },
    { label: "Belgium", value: "EUR", code: "BEL", timezone: "Europe/Brussels" },
    { label: "Belize", value: "BZD", code: "BLZ", timezone: "America/Belize" },
    { label: "Benin", value: "XOF", code: "BEN", timezone: "Africa/Porto-Novo" },
    { label: "Bermuda", value: "BMD", code: "BMU", timezone: "Atlantic/Bermuda" },
    { label: "Bhutan", value: "BTN", code: "BTN", timezone: "Asia/Thimphu" },
    { label: "Bolivia", value: "BOB", code: "BOL", timezone: "America/La_Paz" },
    { label: "Bonaire, Sint Eustatius and Saba", value: "USD", code: "BES", timezone: "America/Kralendijk" },
    { label: "Bosnia and Herzegovina", value: "BAM", code: "BIH", timezone: "Europe/Sarajevo" },
    { label: "Botswana", value: "BWP", code: "BWA", timezone: "Africa/Gaborone" },
    { label: "Bouvet Island", value: "NOK", code: "BVT", timezone: "Europe/Oslo" },
    { label: "Brazil", value: "BRL", code: "BRA", timezone: "America/Sao_Paulo" },
    { label: "British Indian Ocean Territory", value: "USD", code: "IOT", timezone: "Indian/Chagos" },
    { label: "Brunei Darussalam", value: "BND", code: "BRN", timezone: "Asia/Brunei" },
    { label: "Bulgaria", value: "BGN", code: "BGR", timezone: "Europe/Sofia" },
    { label: "Burkina Faso", value: "XOF", code: "BFA", timezone: "Africa/Ouagadougou" },
    { label: "Burundi", value: "BIF", code: "BDI", timezone: "Africa/Gitega" },
    { label: "Cabo Verde", value: "CVE", code: "CPV", timezone: "Atlantic/Cape_Verde" },
    { label: "Cambodia", value: "KHR", code: "KHM", timezone: "Asia/Phnom_Penh" },
    { label: "Cameroon", value: "XAF", code: "CMR", timezone: "Africa/Douala" },
    { label: "Canada", value: "CAD", code: "CAN", timezone: "America/Toronto" },
    { label: "Cayman Islands", value: "KYD", code: "CYM", timezone: "America/Cayman" },
    { label: "Central African Republic", value: "XAF", code: "CAF", timezone: "Africa/Bangui" },
    { label: "Chad", value: "XAF", code: "TCD", timezone: "Africa/Ndjamena" },
    { label: "Chile", value: "CLP", code: "CHL", timezone: "America/Santiago" },
    { label: "China", value: "CNY", code: "CHN", timezone: "Asia/Shanghai" },
    { label: "Christmas Island", value: "AUD", code: "CXR", timezone: "Indian/Christmas" },
    { label: "Cocos (Keeling) Islands", value: "AUD", code: "CCK", timezone: "Indian/Cocos" },
    { label: "Colombia", value: "COP", code: "COL", timezone: "America/Bogota" },
    { label: "Comoros", value: "KMF", code: "COM", timezone: "Indian/Comoro" },
    { label: "Congo", value: "XAF", code: "COG", timezone: "Africa/Brazzaville" },
    { label: "Congo, Democratic Republic of the", value: "CDF", code: "COD", timezone: "Africa/Kinshasa" },
    { label: "Cook Islands", value: "NZD", code: "COK", timezone: "Pacific/Rarotonga" },
    { label: "Costa Rica", value: "CRC", code: "CRI", timezone: "America/Costa_Rica" },
    { label: "Côte d'Ivoire", value: "XOF", code: "CIV", timezone: "Africa/Abidjan" },
    { label: "Croatia", value: "EUR", code: "HRV", timezone: "Europe/Zagreb" },
    { label: "Cuba", value: "CUP", code: "CUB", timezone: "America/Havana" },
    { label: "Curaçao", value: "ANG", code: "CUW", timezone: "America/Curacao" },
    { label: "Cyprus", value: "EUR", code: "CYP", timezone: "Asia/Nicosia" },
    { label: "Czechia", value: "CZK", code: "CZE", timezone: "Europe/Prague" },
    { label: "Denmark", value: "DKK", code: "DNK", timezone: "Europe/Copenhagen" },
    { label: "Djibouti", value: "DJF", code: "DJI", timezone: "Africa/Djibouti" },
    { label: "Dominica", value: "XCD", code: "DMA", timezone: "America/Dominica" },
    { label: "Dominican Republic", value: "DOP", code: "DOM", timezone: "America/Santo_Domingo" },
    { label: "Ecuador", value: "USD", code: "ECU", timezone: "America/Guayaquil" },
    { label: "Egypt", value: "EGP", code: "EGY", timezone: "Africa/Cairo" },
    { label: "El Salvador", value: "USD", code: "SLV", timezone: "America/El_Salvador" },
    { label: "Equatorial Guinea", value: "XAF", code: "GNQ", timezone: "Africa/Malabo" },
    { label: "Eritrea", value: "ERN", code: "ERI", timezone: "Africa/Asmara" },
    { label: "Estonia", value: "EUR", code: "EST", timezone: "Europe/Tallinn" },
    { label: "Eswatini", value: "SZL", code: "SWZ", timezone: "Africa/Mbabane" },
    { label: "Ethiopia", value: "ETB", code: "ETH", timezone: "Africa/Addis_Ababa" },
    { label: "Falkland Islands (Malvinas)", value: "FKP", code: "FLK", timezone: "Atlantic/Stanley" },
    { label: "Faroe Islands", value: "DKK", code: "FRO", timezone: "Atlantic/Faroe" },
    { label: "Fiji", value: "FJD", code: "FJI", timezone: "Pacific/Fiji" },
    { label: "Finland", value: "EUR", code: "FIN", timezone: "Europe/Helsinki" },
    { label: "France", value: "EUR", code: "FRA", timezone: "Europe/Paris" },
    { label: "French Guiana", value: "EUR", code: "GUF", timezone: "America/Cayenne" },
    { label: "French Polynesia", value: "XPF", code: "PYF", timezone: "Pacific/Tahiti" },
    { label: "French Southern Territories", value: "EUR", code: "ATF", timezone: "Indian/Kerguelen" },
    { label: "Gabon", value: "XAF", code: "GAB", timezone: "Africa/Libreville" },
    { label: "Gambia", value: "GMD", code: "GMB", timezone: "Africa/Banjul" },
    { label: "Georgia", value: "GEL", code: "GEO", timezone: "Asia/Tbilisi" },
    { label: "Germany", value: "EUR", code: "DEU", timezone: "Europe/Berlin" },
    { label: "Ghana", value: "GHS", code: "GHA", timezone: "Africa/Accra" },
    { label: "Gibraltar", value: "GIP", code: "GIB", timezone: "Europe/Gibraltar" },
    { label: "Greece", value: "EUR", code: "GRC", timezone: "Europe/Athens" },
    { label: "Greenland", value: "DKK", code: "GRL", timezone: "America/Nuuk" },
    { label: "Grenada", value: "XCD", code: "GRD", timezone: "America/Grenada" },
    { label: "Guadeloupe", value: "EUR", code: "GLP", timezone: "America/Guadeloupe" },
    { label: "Guam", value: "USD", code: "GUM", timezone: "Pacific/Guam" },
    { label: "Guatemala", value: "GTQ", code: "GTM", timezone: "America/Guatemala" },
    { label: "Guernsey", value: "GBP", code: "GGY", timezone: "Europe/Guernsey" },
    { label: "Guinea", value: "GNF", code: "GIN", timezone: "Africa/Conakry" },
    { label: "Guinea-Bissau", value: "XOF", code: "GNB", timezone: "Africa/Bissau" },
    { label: "Guyana", value: "GYD", code: "GUY", timezone: "America/Guyana" },
    { label: "Haiti", value: "HTG", code: "HTI", timezone: "America/Port-au-Prince" },
    { label: "Heard Island and McDonald Islands", value: "AUD", code: "HMD", timezone: "Indian/Maldives" },
    { label: "Holy See", value: "EUR", code: "VAT", timezone: "Europe/Vatican" },
    { label: "Honduras", value: "HNL", code: "HND", timezone: "America/Tegucigalpa" },
    { label: "Hong Kong", value: "HKD", code: "HKG", timezone: "Asia/Hong_Kong" },
    { label: "Hungary", value: "HUF", code: "HUN", timezone: "Europe/Budapest" },
    { label: "Iceland", value: "ISK", code: "ISL", timezone: "Atlantic/Reykjavik" },
    { label: "India", value: "INR", code: "IND", timezone: "Asia/Kolkata" },
    { label: "Indonesia", value: "IDR", code: "IDN", timezone: "Asia/Jakarta" },
    { label: "Iran", value: "IRR", code: "IRN", timezone: "Asia/Tehran" },
    { label: "Iraq", value: "IQD", code: "IRQ", timezone: "Asia/Baghdad" },
    { label: "Ireland", value: "EUR", code: "IRL", timezone: "Europe/Dublin" },
    { label: "Isle of Man", value: "GBP", code: "IMN", timezone: "Europe/Isle_of_Man" },
    { label: "Israel", value: "ILS", code: "ISR", timezone: "Asia/Jerusalem" },
    { label: "Italy", value: "EUR", code: "ITA", timezone: "Europe/Rome" },
    { label: "Jamaica", value: "JMD", code: "JAM", timezone: "America/Jamaica" },
    { label: "Japan", value: "JPY", code: "JPN", timezone: "Asia/Tokyo" },
    { label: "Jersey", value: "GBP", code: "JEY", timezone: "Europe/Jersey" },
    { label: "Jordan", value: "JOD", code: "JOR", timezone: "Asia/Amman" },
    { label: "Kazakhstan", value: "KZT", code: "KAZ", timezone: "Asia/Almaty" },
    { label: "Kenya", value: "KES", code: "KEN", timezone: "Africa/Nairobi" },
    { label: "Kiribati", value: "AUD", code: "KIR", timezone: "Pacific/Tarawa" },
    { label: "Korea, Democratic People's Republic of", value: "KPW", code: "PRK", timezone: "Asia/Pyongyang" },
    { label: "Korea, Republic of", value: "KRW", code: "KOR", timezone: "Asia/Seoul" },
    { label: "Kuwait", value: "KWD", code: "KWT", timezone: "Asia/Kuwait" },
    { label: "Kyrgyzstan", value: "KGS", code: "KGZ", timezone: "Asia/Bishkek" },
    { label: "Lao People's Democratic Republic", value: "LAK", code: "LAO", timezone: "Asia/Vientiane" },
    { label: "Latvia", value: "EUR", code: "LVA", timezone: "Europe/Riga" },
    { label: "Lebanon", value: "LBP", code: "LBN", timezone: "Asia/Beirut" },
    { label: "Lesotho", value: "LSL", code: "LSO", timezone: "Africa/Maseru" },
    { label: "Liberia", value: "LRD", code: "LBR", timezone: "Africa/Monrovia" },
    { label: "Libya", value: "LYD", code: "LBY", timezone: "Africa/Tripoli" },
    { label: "Liechtenstein", value: "CHF", code: "LIE", timezone: "Europe/Vaduz" },
    { label: "Lithuania", value: "EUR", code: "LTU", timezone: "Europe/Vilnius" },
    { label: "Luxembourg", value: "EUR", code: "LUX", timezone: "Europe/Luxembourg" },
    { label: "Macao", value: "MOP", code: "MAC", timezone: "Asia/Macau" },
    { label: "Madagascar", value: "MGA", code: "MDG", timezone: "Indian/Antananarivo" },
    { label: "Malawi", value: "MWK", code: "MWI", timezone: "Africa/Blantyre" },
    { label: "Malaysia", value: "MYR", code: "MYS", timezone: "Asia/Kuala_Lumpur" },
    { label: "Maldives", value: "MVR", code: "MDV", timezone: "Indian/Maldives" },
    { label: "Mali", value: "XOF", code: "MLI", timezone: "Africa/Bamako" },
    { label: "Malta", value: "EUR", code: "MLT", timezone: "Europe/Malta" },
    { label: "Marshall Islands", value: "USD", code: "MHL", timezone: "Pacific/Majuro" },
    { label: "Martinique", value: "EUR", code: "MTQ", timezone: "America/Martinique" },
    { label: "Mauritania", value: "MRU", code: "MRT", timezone: "Africa/Nouakchott" },
    { label: "Mauritius", value: "MUR", code: "MUS", timezone: "Indian/Mauritius" },
    { label: "Mayotte", value: "EUR", code: "MYT", timezone: "Indian/Mayotte" },
    { label: "Mexico", value: "MXN", code: "MEX", timezone: "America/Mexico_City" },
    { label: "Micronesia", value: "USD", code: "FSM", timezone: "Pacific/Pohnpei" },
    { label: "Moldova", value: "MDL", code: "MDA", timezone: "Europe/Chisinau" },
    { label: "Monaco", value: "EUR", code: "MCO", timezone: "Europe/Monaco" },
    { label: "Mongolia", value: "MNT", code: "MNG", timezone: "Asia/Ulaanbaatar" },
    { label: "Montenegro", value: "EUR", code: "MNE", timezone: "Europe/Podgorica" },
    { label: "Montserrat", value: "XCD", code: "MSR", timezone: "America/Montserrat" },
    { label: "Morocco", value: "MAD", code: "MAR", timezone: "Africa/Casablanca" },
    { label: "Mozambique", value: "MZN", code: "MOZ", timezone: "Africa/Maputo" },
    { label: "Myanmar", value: "MMK", code: "MMR", timezone: "Asia/Yangon" },
    { label: "Namibia", value: "NAD", code: "NAM", timezone: "Africa/Windhoek" },
    { label: "Nauru", value: "AUD", code: "NRU", timezone: "Pacific/Nauru" },
    { label: "Nepal", value: "NPR", code: "NPL", timezone: "Asia/Kathmandu" },
    { label: "Netherlands", value: "EUR", code: "NLD", timezone: "Europe/Amsterdam" },
    { label: "New Caledonia", value: "XPF", code: "NCL", timezone: "Pacific/Noumea" },
    { label: "New Zealand", value: "NZD", code: "NZL", timezone: "Pacific/Auckland" },
    { label: "Nicaragua", value: "NIO", code: "NIC", timezone: "America/Managua" },
    { label: "Niger", value: "XOF", code: "NER", timezone: "Africa/Niamey" },
    { label: "Nigeria", value: "NGN", code: "NGA", timezone: "Africa/Lagos" },
    { label: "Niue", value: "NZD", code: "NIU", timezone: "Pacific/Niue" },
    { label: "Norfolk Island", value: "AUD", code: "NFK", timezone: "Pacific/Norfolk" },
    { label: "North Macedonia", value: "MKD", code: "MKD", timezone: "Europe/Skopje" },
    { label: "Northern Mariana Islands", value: "USD", code: "MNP", timezone: "Pacific/Saipan" },
    { label: "Norway", value: "NOK", code: "NOR", timezone: "Europe/Oslo" },
    { label: "Oman", value: "OMR", code: "OMN", timezone: "Asia/Muscat" },
    { label: "Pakistan", value: "PKR", code: "PAK", timezone: "Asia/Karachi" },
    { label: "Palau", value: "USD", code: "PLW", timezone: "Pacific/Palau" },
    { label: "Palestine, State of", value: "ILS", code: "PSE", timezone: "Asia/Gaza" },
    { label: "Panama", value: "PAB", code: "PAN", timezone: "America/Panama" },
    { label: "Papua New Guinea", value: "PGK", code: "PNG", timezone: "Pacific/Port_Moresby" },
    { label: "Paraguay", value: "PYG", code: "PRY", timezone: "America/Asuncion" },
    { label: "Peru", value: "PEN", code: "PER", timezone: "America/Lima" },
    { label: "Philippines", value: "PHP", code: "PHL", timezone: "Asia/Manila" },
    { label: "Pitcairn", value: "NZD", code: "PCN", timezone: "Pacific/Pitcairn" },
    { label: "Poland", value: "PLN", code: "POL", timezone: "Europe/Warsaw" },
    { label: "Portugal", value: "EUR", code: "PRT", timezone: "Europe/Lisbon" },
    { label: "Puerto Rico", value: "USD", code: "PRI", timezone: "America/Puerto_Rico" },
    { label: "Qatar", value: "QAR", code: "QAT", timezone: "Asia/Qatar" },
    { label: "Réunion", value: "EUR", code: "REU", timezone: "Indian/Reunion" },
    { label: "Romania", value: "RON", code: "ROU", timezone: "Europe/Bucharest" },
    { label: "Russian Federation", value: "RUB", code: "RUS", timezone: "Europe/Moscow" },
    { label: "Rwanda", value: "RWF", code: "RWA", timezone: "Africa/Kigali" },
    { label: "Saint Barthélemy", value: "EUR", code: "BLM", timezone: "America/St_Barthelemy" },
    { label: "Saint Helena, Ascension and Tristan da Cunha", value: "SHP", code: "SHN", timezone: "Atlantic/St_Helena" },
    { label: "Saint Kitts and Nevis", value: "XCD", code: "KNA", timezone: "America/St_Kitts" },
    { label: "Saint Lucia", value: "XCD", code: "LCA", timezone: "America/St_Lucia" },
    { label: "Saint Martin (French part)", value: "EUR", code: "MAF", timezone: "America/Marigot" },
    { label: "Saint Pierre and Miquelon", value: "EUR", code: "SPM", timezone: "America/Miquelon" },
    { label: "Saint Vincent and the Grenadines", value: "XCD", code: "VCT", timezone: "America/St_Vincent" },
    { label: "Samoa", value: "WST", code: "WSM", timezone: "Pacific/Apia" },
    { label: "San Marino", value: "EUR", code: "SMR", timezone: "Europe/San_Marino" },
    { label: "Sao Tome and Principe", value: "STN", code: "STP", timezone: "Africa/Sao_Tome" },
    { label: "Saudi Arabia", value: "SAR", code: "SAU", timezone: "Asia/Riyadh" },
    { label: "Senegal", value: "XOF", code: "SEN", timezone: "Africa/Dakar" },
    { label: "Serbia", value: "RSD", code: "SRB", timezone: "Europe/Belgrade" },
    { label: "Seychelles", value: "SCR", code: "SYC", timezone: "Indian/Mahe" },
    { label: "Sierra Leone", value: "SLL", code: "SLE", timezone: "Africa/Freetown" },
    { label: "Singapore", value: "SGD", code: "SGP", timezone: "Asia/Singapore" },
    { label: "Sint Maarten (Dutch part)", value: "ANG", code: "SXM", timezone: "America/Lower_Princes" },
    { label: "Slovakia", value: "EUR", code: "SVK", timezone: "Europe/Bratislava" },
    { label: "Slovenia", value: "EUR", code: "SVN", timezone: "Europe/Ljubljana" },
    { label: "Solomon Islands", value: "SBD", code: "SLB", timezone: "Pacific/Guadalcanal" },
    { label: "Somalia", value: "SOS", code: "SOM", timezone: "Africa/Mogadishu" },
    { label: "South Africa", value: "ZAR", code: "ZAF", timezone: "Africa/Johannesburg" },
    { label: "South Georgia and the South Sandwich Islands", value: "GBP", code: "SGS", timezone: "Atlantic/South_Georgia" },
    { label: "South Sudan", value: "SSP", code: "SSD", timezone: "Africa/Juba" },
    { label: "Spain", value: "EUR", code: "ESP", timezone: "Europe/Madrid" },
    { label: "Sri Lanka", value: "LKR", code: "LKA", timezone: "Asia/Colombo" },
    { label: "Sudan", value: "SDG", code: "SDN", timezone: "Africa/Khartoum" },
    { label: "Suriname", value: "SRD", code: "SUR", timezone: "America/Paramaribo" },
    { label: "Svalbard and Jan Mayen", value: "NOK", code: "SJM", timezone: "Arctic/Longyearbyen" },
    { label: "Sweden", value: "SEK", code: "SWE", timezone: "Europe/Stockholm" },
    { label: "Switzerland", value: "CHF", code: "CHE", timezone: "Europe/Zurich" },
    { label: "Syrian Arab Republic", value: "SYP", code: "SYR", timezone: "Asia/Damascus" },
    { label: "Taiwan", value: "TWD", code: "TWN", timezone: "Asia/Taipei" },
    { label: "Tajikistan", value: "TJS", code: "TJK", timezone: "Asia/Dushanbe" },
    { label: "Tanzania", value: "TZS", code: "TZA", timezone: "Africa/Dar_es_Salaam" },
    { label: "Thailand", value: "THB", code: "THA", timezone: "Asia/Bangkok" },
    { label: "Timor-Leste", value: "USD", code: "TLS", timezone: "Asia/Dili" },
    { label: "Togo", value: "XOF", code: "TGO", timezone: "Africa/Lome" },
    { label: "Tokelau", value: "NZD", code: "TKL", timezone: "Pacific/Fakaofo" },
    { label: "Tonga", value: "TOP", code: "TON", timezone: "Pacific/Tongatapu" },
    { label: "Trinidad and Tobago", value: "TTD", code: "TTO", timezone: "America/Port_of_Spain" },
    { label: "Tunisia", value: "TND", code: "TUN", timezone: "Africa/Tunis" },
    { label: "Turkey", value: "TRY", code: "TUR", timezone: "Europe/Istanbul" },
    { label: "Turkmenistan", value: "TMT", code: "TKM", timezone: "Asia/Ashgabat" },
    { label: "Turks and Caicos Islands", value: "USD", code: "TCA", timezone: "America/Grand_Turk" },
    { label: "Tuvalu", value: "AUD", code: "TUV", timezone: "Pacific/Funafuti" },
    { label: "Uganda", value: "UGX", code: "UGA", timezone: "Africa/Kampala" },
    { label: "Ukraine", value: "UAH", code: "UKR", timezone: "Europe/Kyiv" },
    { label: "United Arab Emirates", value: "AED", code: "ARE", timezone: "Asia/Dubai" },
    { label: "United Kingdom", value: "GBP", code: "GBR", timezone: "Europe/London" },
    { label: "United States", value: "USD", code: "USA", timezone: "America/New_York" },
    { label: "United States Minor Outlying Islands", value: "USD", code: "UMI", timezone: "Pacific/Wake" },
    { label: "Uruguay", value: "UYU", code: "URY", timezone: "America/Montevideo" },
    { label: "Uzbekistan", value: "UZS", code: "UZB", timezone: "Asia/Tashkent" },
    { label: "Vanuatu", value: "VUV", code: "VUT", timezone: "Pacific/Efate" },
    { label: "Venezuela", value: "VES", code: "VEN", timezone: "America/Caracas" },
    { label: "Viet Nam", value: "VND", code: "VNM", timezone: "Asia/Ho_Chi_Minh" },
    { label: "Virgin Islands (British)", value: "USD", code: "VGB", timezone: "America/Tortola" },
    { label: "Virgin Islands (U.S.)", value: "USD", code: "VIR", timezone: "America/St_Thomas" },
    { label: "Wallis and Futuna", value: "XPF", code: "WLF", timezone: "Pacific/Wallis" },
    { label: "Western Sahara", value: "MAD", code: "ESH", timezone: "Africa/El_Aaiun" },
    { label: "Yemen", value: "YER", code: "YEM", timezone: "Asia/Aden" },
    { label: "Zambia", value: "ZMW", code: "ZMB", timezone: "Africa/Lusaka" },
    { label: "Zimbabwe", value: "ZWL", code: "ZWE", timezone: "Africa/Harare" }
]

export default countries